version: 1.0.{build}

install:
- cmd: >-
    gem install --source http://rubygems.org nokogiri -v 1.6.8.1

    generate.bat
build_script:
- cmd: build.bat

test_script:
- cmd: >-
    unit_test.bat

    appveyor_test.bat
      
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/280capmarkets/api/v2/package
  api_key:
      secure: pBTga3EQD0q+d1HVCa/5jGmsk2+DP49SsMtAq7EyfhJYC6kPvZQdbzvJ3DlcMbd9
  skip_symbols: true
  on:
      branch: master