version: 1.0.{build}

install:
- dir C:\
- set PATH=C:\Ruby26-x64\bin;%PATH%
- ruby -v
- ps: |
    ruby -v
    gem install nokogiri
    ruby generator\generate.rb

before_test:
- ruby -v

build_script:
- ps: dotnet build -c Release

test_script:
- ps: |
    dotnet test -c Release --no-build --no-restore UnitTests -l trx
    .\acceptance_test.ps1
      
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/280capmarkets/api/v2/package
  api_key:
      secure: pBTga3EQD0q+d1HVCa/5jGmsk2+DP49SsMtAq7EyfhJYC6kPvZQdbzvJ3DlcMbd9
  skip_symbols: true
  on:
      branch: master